### ISSUE TITLE
CSP stop js from execution

### ISSUE THREAD

**Issue by Scrooge20291224** [mikecann/Chrome-Crawler#3]
### lib/jquery-1.4.3.min.js:38
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-/wBYH7/YAgZzT26DQ6O8rVvO/h/Ump6C27AYl+iO26I='), or a nonce ('nonce-...') is required to enable inline execution.

### options.html:6
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-6t+m4O33KzMZpZk0cSWS2jTGy5danRMyNiQH1JiRt04='), or a nonce ('nonce-...') is required to enable inline execution.

### options.html:32
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by mikecann** [comment]
Hi,

Ye this project is really old and TBH I dont really plan on updating it. Feel free to open a PR. Otherwise you may have more luck with my other project "Recursive": https://mikecann.co.uk/html/recursive-explore-the-endless-web
